using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MailArchiver.Migrations
{
    /// <inheritdoc />
    public partial class MigrateV2606_2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create DailySummaries table for AI-generated daily email summaries
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS mail_archiver.""DailySummaries"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PeriodStartUtc"" timestamp without time zone NOT NULL,
                    ""PeriodEndUtc"" timestamp without time zone NOT NULL,
                    ""CreatedAtUtc"" timestamp without time zone NOT NULL,
                    ""EmailCount"" integer NOT NULL,
                    ""OverviewText"" text NOT NULL DEFAULT '',
                    ""ItemsJson"" text NOT NULL DEFAULT '[]',
                    ""Model"" character varying(100) NOT NULL DEFAULT '',
                    ""IsSuccess"" boolean NOT NULL DEFAULT TRUE,
                    ""ErrorMessage"" text NULL,
                    CONSTRAINT ""PK_DailySummaries"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_DailySummaries_CreatedAtUtc""
                ON mail_archiver.""DailySummaries"" (""CreatedAtUtc"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS mail_archiver.""DailySummaries"";
            ");
        }
    }
}
